name: Sync with Hugging Face Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync with Hugging Face (DeepfloydIF)
      uses: nateraw/huggingface-sync-action@v0.0.4
      with:
        github_repo_id: lunarflu/huggingbots
        huggingface_repo_id: lunarflu/deepfloydIF-bot
        repo_type: space
        space_sdk: gradio
        hf_token: ${{ secrets.HF_TOKEN_WRITE }}
        subdirectory: deepfloydIf
        files: |
          /deepfloydif/app.py: lunarflu/deepfloydIF-bot
          /deepfloydif/requirements.txt: lunarflu/deepfloydIF-bot

    - name: Sync with Hugging Face (Falcon180b)
      uses: nateraw/huggingface-sync-action@v0.0.4
      with:
        github_repo_id: lunarflu/huggingbots
        huggingface_repo_id: lunarflu/falcon180b-bot
        repo_type: space
        space_sdk: gradio
        hf_token: ${{ secrets.HF_TOKEN_WRITE }}
        subdirectory: falcon180b
        files: |
          /falcon180b/app.py: lunarflu/falcon180b-bot
          /falcon180b/requirements.txt: lunarflu/falcon180b-bot
